/*
 * Input operand A for the toy_adder HWPE.
 *
 * In a real flow this file would be auto-generated by a golden-model
 * script, just like redmule's x_input.h / w_input.h.
 */

#ifndef __A_INPUT_H__
#define __A_INPUT_H__

#define OPERAND_A  42

#endif /* __A_INPUT_H__ */
