/*
 * Input operand B for the toy_adder HWPE.
 *
 * In a real flow this file would be auto-generated by a golden-model
 * script, just like redmule's x_input.h / w_input.h.
 */

#ifndef __B_INPUT_H__
#define __B_INPUT_H__

#define OPERAND_B  17

#endif /* __B_INPUT_H__ */
