/*
 * Matrix B input for the lemon_dot HWPE.
 *
 * B is K × N = 4 × 4, stored row-major.
 * Generated by gen_stimuli.py (or hand-written for this toy example).
 *
 *     | 1  2  0  0 |
 * B = | 0  1  2  0 |
 *     | 0  0  1  2 |
 *     | 2  0  0  1 |
 */

#ifndef __MATRIX_B_H__
#define __MATRIX_B_H__

#define DOT_N  4

#define MATRIX_B_DATA  { \
    1, 2, 0, 0,         \
    0, 1, 2, 0,         \
    0, 0, 1, 2,         \
    2, 0, 0, 1          \
}

#endif /* __MATRIX_B_H__ */
