/*
 * Matrix A input for the lemon_dot HWPE.
 *
 * A is M × K = 4 × 4, stored row-major.
 * Generated by gen_stimuli.py (or hand-written for this toy example).
 *
 *     |  1   2   3   4 |
 * A = |  5   6   7   8 |
 *     |  9  10  11  12 |
 *     | 13  14  15  16 |
 */

#ifndef __MATRIX_A_H__
#define __MATRIX_A_H__

#define DOT_M  4
#define DOT_K  4

#define MATRIX_A_DATA  { \
     1,  2,  3,  4,    \
     5,  6,  7,  8,    \
     9, 10, 11, 12,    \
    13, 14, 15, 16     \
}

#endif /* __MATRIX_A_H__ */
