#!/usr/bin/env python3
"""
Lemon Dot HWPE — Test vector generator

Generates inc/matrix_a.h, inc/matrix_b.h, and inc/golden.h for the
lemon_dot HWPE test.

Usage:
    python3 gen_stimuli.py                     # defaults: M=K=N=4
    python3 gen_stimuli.py --m 8 --k 4 --n 8  # custom dimensions
    python3 gen_stimuli.py --random             # random values

The output matrices use int32_t elements and row-major storage,
matching what the HWPE model expects.
"""

import argparse
import os
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INC_DIR    = os.path.join(SCRIPT_DIR, "inc")


def gen_matrix_a(M, K, random=False, seed=42):
    """Generate matrix A (M × K)."""
    if random:
        rng = np.random.default_rng(seed)
        return rng.integers(-10, 11, size=(M, K), dtype=np.int32)
    else:
        # Simple sequential values 1..M*K (easy to verify by hand)
        return np.arange(1, M * K + 1, dtype=np.int32).reshape(M, K)


def gen_matrix_b(K, N, random=False, seed=43):
    """Generate matrix B (K × N)."""
    if random:
        rng = np.random.default_rng(seed)
        return rng.integers(-10, 11, size=(K, N), dtype=np.int32)
    else:
        # Circulant-ish matrix that's interesting but hand-verifiable
        B = np.zeros((K, N), dtype=np.int32)
        for i in range(K):
            B[i, i % N] = 1
            B[i, (i + 1) % N] = 2
        return B


def write_header(path, guard, content):
    """Write a C header file."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(f"/* Auto-generated by gen_stimuli.py — do not edit */\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write(content)
        f.write(f"\n#endif /* {guard} */\n")
    print(f"  Wrote {path}")


def matrix_to_c_initializer(mat):
    """Convert a numpy matrix to a C initializer string."""
    rows, cols = mat.shape
    lines = []
    for i in range(rows):
        vals = ", ".join(f"{int(v):4d}" for v in mat[i])
        lines.append(f"    {vals}")
    return "{{ \\\n" + ", \\\n".join(lines) + "  \\\n}}"


def format_matrix(name, mat):
    """Pretty-print a matrix for the header comment."""
    rows, cols = mat.shape
    lines = []
    for i in range(rows):
        vals = " ".join(f"{int(v):4d}" for v in mat[i])
        prefix = f" {name} = " if i == rows // 2 else "       "
        lines.append(f" *{prefix}| {vals} |")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate lemon_dot test vectors")
    parser.add_argument("--m", type=int, default=4, help="Rows of A / C (default: 4)")
    parser.add_argument("--k", type=int, default=4, help="Inner dimension (default: 4)")
    parser.add_argument("--n", type=int, default=4, help="Cols of B / C (default: 4)")
    parser.add_argument("--random", action="store_true", help="Use random values")
    parser.add_argument("--seed", type=int, default=42, help="Random seed (default: 42)")
    args = parser.parse_args()

    M, K, N = args.m, args.k, args.n
    assert M <= 16 and K <= 16 and N <= 16, "Max dimension is 16"

    print(f"Generating test vectors: A({M}×{K}) × B({K}×{N}) → C({M}×{N})")

    A = gen_matrix_a(M, K, random=args.random, seed=args.seed)
    B = gen_matrix_b(K, N, random=args.random, seed=args.seed + 1)
    C = A @ B   # numpy matrix multiply

    print(f"\nA =\n{A}\n\nB =\n{B}\n\nC = A × B =\n{C}\n")

    # ---- matrix_a.h ----
    write_header(
        os.path.join(INC_DIR, "matrix_a.h"),
        "__MATRIX_A_H__",
        f"/*\n{format_matrix('A', A)}\n */\n\n"
        f"#define DOT_M  {M}\n"
        f"#define DOT_K  {K}\n\n"
        f"#define MATRIX_A_DATA  {matrix_to_c_initializer(A)}\n"
    )

    # ---- matrix_b.h ----
    write_header(
        os.path.join(INC_DIR, "matrix_b.h"),
        "__MATRIX_B_H__",
        f"/*\n{format_matrix('B', B)}\n */\n\n"
        f"#define DOT_N  {N}\n\n"
        f"#define MATRIX_B_DATA  {matrix_to_c_initializer(B)}\n"
    )

    # ---- golden.h ----
    write_header(
        os.path.join(INC_DIR, "golden.h"),
        "__GOLDEN_H__",
        f"/*\n{format_matrix('C', C)}\n */\n\n"
        f"#define GOLDEN_DATA  {matrix_to_c_initializer(C)}\n"
    )

    print(f"\nDone! Test vectors written to {INC_DIR}/")


if __name__ == "__main__":
    main()
